In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.5.0'

In [3]:
from tensorflow.keras.datasets import mnist
from tensorflow.keras.utils import to_categorical

In [4]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [5]:
x_train.shape

(60000, 28, 28)

In [6]:
y_train[:10]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4], dtype=uint8)

In [8]:
y_train_oe = y_train%2
y_test_oe = y_test%2

In [9]:
y_train_hot = to_categorical(y_train, num_classes=10)
y_test_hot = to_categorical(y_test, num_classes=10)

y_train_oe_hot = to_categorical(y_train_oe, num_classes=2)
y_test_oe_hot = to_categorical(y_test_oe, num_classes=2)

In [10]:
y_train_hot[:10]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)

In [11]:
y_train[:10]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4], dtype=uint8)

In [12]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Reshape

In [24]:
in_layer = Input(shape=[28, 28])
reshape = Reshape([784])(in_layer)
d1 = Dense(500, activation="relu")(reshape)
d2 = Dense(200, activation="relu")(d1)
d3 = Dense(50, activation="relu")(d2)
out_layer_1 = Dense(10, activation="softmax")(d3)
out_layer_2 = Dense(2, activation="softmax")(out_layer_1)

In [25]:
model = Model(in_layer, [out_layer_1, out_layer_2])

In [26]:
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 28, 28)]          0         
_________________________________________________________________
reshape_1 (Reshape)          (None, 784)               0         
_________________________________________________________________
dense_6 (Dense)              (None, 500)               392500    
_________________________________________________________________
dense_7 (Dense)              (None, 200)               100200    
_________________________________________________________________
dense_8 (Dense)              (None, 50)                10050     
_________________________________________________________________
dense_9 (Dense)              (None, 10)                510       
_________________________________________________________________
dense_10 (Dense)             (None, 2)                 22  

In [27]:
model.compile(optimizer="adam", loss="categorical_crossentropy", metrics=["accuracy"])

In [28]:
model.fit(x_train, [y_train_hot, y_train_oe_hot], batch_size=600, epochs=10)

Epoch 1/10
100/100 [==============================] - 2s 16ms/step - loss: 4.7405 - dense_9_loss: 4.0381 - dense_10_loss: 0.7023 - dense_9_accuracy: 0.6902 - dense_10_accuracy: 0.5386
Epoch 2/10
100/100 [==============================] - 2s 16ms/step - loss: 1.1046 - dense_9_loss: 0.4957 - dense_10_loss: 0.6089 - dense_9_accuracy: 0.8729 - dense_10_accuracy: 0.7086
Epoch 3/10
100/100 [==============================] - 2s 18ms/step - loss: 0.8673 - dense_9_loss: 0.3392 - dense_10_loss: 0.5281 - dense_9_accuracy: 0.9146 - dense_10_accuracy: 0.7549
Epoch 4/10
100/100 [==============================] - 2s 17ms/step - loss: 0.7142 - dense_9_loss: 0.2543 - dense_10_loss: 0.4599 - dense_9_accuracy: 0.9349 - dense_10_accuracy: 0.8235
Epoch 5/10
100/100 [==============================] - 2s 19ms/step - loss: 0.5961 - dense_9_loss: 0.1941 - dense_10_loss: 0.4019 - dense_9_accuracy: 0.9483 - dense_10_accuracy: 0.8627
Epoch 6/10
100/100 [==============================] - 2s 19ms/step - loss: 0.510

In [29]:
model.evaluate(x_test, [y_test_hot, y_test_oe_hot], verbose=0)

[0.43374112248420715,
 0.21738998591899872,
 0.21635115146636963,
 0.9639000296592712,
 0.9833999872207642]

In [30]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread("../data/two.png")
small = cv2.resize(img, [28, 28])
gray = small.mean(axis=2)

gray = (gray > 100).astype(int) * 255

[o1, o2] = model.predict(np.array([gray]))

print(o1.argmax(axis=1))

[2]


In [31]:
model.save("mnisttf", save_format="tf")

INFO:tensorflow:Assets written to: mnisttf/assets
