In [3]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [17]:
X, y = make_blobs(n_samples=1000, n_features=2, centers=2, random_state=42)

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)

In [19]:
class CustomLogisticReg:
    
    def __init__(self, lr=1, max_iters=100):
        self.lr = lr
        self.max_iters = max_iters
        
    def fit(self, X, y):
        
        ya = y.reshape([-1, 1])
        
        self.coef_ = np.zeros([X.shape[1], 1])
        self.intercept_ = 0
        
        for i in range(self.max_iters):
            
            yp = self.__predict(X)
            
            delm = (np.dot(X.T, (ya - yp)) / len(X)) * self.lr
            delc = (ya - yp).mean() * self.lr
            
            self.coef_ = self.coef_ - delm
            self.intercept_ = self.intercept_ - delc
            
    def __predict(self, X):
        g = np.dot(X, self.coef_) + self.intercept_
        yp = 1 / (1 + np.exp(g))
        return yp
    
    def predict(self, X):
        g = np.dot(X, self.coef_) + self.intercept_
        yp = 1 / (1 + np.exp(g))
        
        return (yp > .5).astype(int).flatten()
    
    def score(self, X, y):
        yp = self.predict(X)
        return (yp == y).mean()

In [20]:
model = CustomLogisticReg()

In [21]:
model.fit(X_train, y_train)

In [22]:
model.predict(X_test[:10])

array([1, 0, 1, 1, 0, 1, 0, 0, 0, 1])

In [23]:
y_test[:10]

array([1, 0, 1, 1, 0, 1, 0, 0, 0, 1])

In [24]:
model.score(X_test, y_test)

1.0

In [25]:
model.coef_

array([[-2.52560745],
       [ 0.80170508]])

In [26]:
model.intercept_

-0.2656613342561513